### PR TITLE
Added level shift, damping options for CCSD

### PR DESCRIPTION
**Pull request by abhishekkhedkar09**
Added some more solver options for CCSD cluster solver: level shift, iterative damping, DIIS space, and DIIS start cycle

### CODE REVIEW

**Comment by ghb24** [comment]
This fails tests? Presumably it is changing the defaults for the CCSD solvers when you explicitly pass in e.g. diis_space=None?

**Comment by maxnus** [comment]
The test failure is unrelated to these changes:
FAILED vayesta/tests/ewf/test_h2.py::Test_UFCI_dissoc::test_energy - ValueError: cannot reshape array of size 0 into shape (0,0)

However, could you please change the default of `level_shift` to `None`, rather than `0.0`? Thanks.

**Comment by obackhouse** [comment]
Any idea why that test is failing @abhishekkhedkar09 ?

**Comment by ghb24** [comment]
Tests now passing after merge with master.

**Comment by abhishekkhedkar09** [comment]
> Any idea why that test is failing @abhishekkhedkar09 ?

I believe the test failure was related to what Charlie added as a fix for incore/outcore defaults.

**Review by obackhouse — APPROVED** [review]

**Pull request merged**
