### PR TITLE
Fix bug in UHF 2dm cumulant 

### PR DESCRIPTION
**Pull request by basilib**
Contraction of vvVV block with eris when nvira xor nvirb is zero, fails.
Added check to skip that contribution when necessary.

### CODE REVIEW

**Comment by maxnus** [comment]
Thanks for reporting! Can you verify that the alternative fix I pushed also works for your case?

**Comment by basilib** [comment]
Yeah, that works too.

I've added the autoconversion of ROHF to UHF to this PR as well.

**Comment by maxnus** [comment]
> I've added the autoconversion of ROHF to UHF to this PR as well.

OK great. Alternatively, the conversion could be done in `qemb.init_mf`, which is called by all subclasses.

**Comment by basilib** [comment]
That was how I tried to do it initially but setting is_rhf, is_uhf and spinsym appropriately didn't work. Maybe there is some other key attribute I missed.

**Comment by maxnus** [comment]
You wouldn't need to set these - anyway this way is fine too

**Comment by maxnus** [comment]
Please use more meaningful branch name than `fix` in future - thanks :+1:

**Pull request merged**
